### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by redrick** [mimischi/dokku-sentry#3]
I got hopefully one last problem here...

I am not able to send any emails from sentry.... 

I followed how you described the stuff and copied over configs from my previous server, using mailgun there... 

onyl things I am still getting from the app is internal timeout:

```python
def send_messages(messages, fail_silently=False):
    connection = get_connection(fail_silently=fail_silently)
>>    sent = connection.send_messages(messages)
    metrics.incr('email.sent', len(messages))
```

I got it configured like this:

<img width="873" alt="screen shot 2017-12-03 at 16 55 33" src="https://user-images.githubusercontent.com/865364/33527100-270e6850-d84b-11e7-9abc-5c88c1227f32.png">

I don't have to be using mailgun o this part, but I  pay for that one so got many free emails monthly, will be more than happy if you suggest something that works for you or so...

Let me know if you need more information, I know I described it badly, but I got no idea where to move here...

Many thanks :)

**Comment by mimischi** [comment]
What's the error message that you get? I haven't tried using it with mailgun yet. The server we've been using it with just has access to an open SMTP port, so we don't really need to do any configuration on that part.

**Comment by redrick** [comment]
Will this screen help?

![2017-12-03-17-10-sentry antas cz](https://user-images.githubusercontent.com/865364/33527220-fe89ee3e-d84c-11e7-9105-bd6c0fa1782d.png)

**Comment by mimischi** [comment]
Has the same configuration worked for you before migrating to this project? I'm wondering whether mailgun is correctly supported by Sentry?

**Comment by redrick** [comment]
It actually did, but as I am looking at this, the difference may be that I got it deployed as `herokuish` and now deploying as `dockerfile`... cannot see any difference other there...

I am trying to add different domain and getting it verified on mailgun...

I have no idea where to start looking here... seems ok to me and still throws that timeout... hmm

**Comment by redrick** [comment]
So far by digging through all the constants and so I found that this var here:

```
dokku config:set --no-restart sentry SENTRY_EMAIL_USERNAME=<yourusername>
```

Should be replaced with:

```
dokku config:set --no-restart sentry SENTRY_EMAIL_USER=<yourusername>
```

That was not showing in Mail settings correctly... but even after setting that up I am not able to send emails... still timeout... I was so certain I found it :(

**Comment by redrick** [comment]
OK solved it...

So scratch what I said... after some hours spent on this I figured, cannot be a problem with the sentry app.... no way that has to work like this...

As this is DevOps I am using cheap server for it -> scaleway.com....

And that is where the problem is... they block smtp by default.... these guys here saved me -> https://community.online.net/t/solved-smtp-connection-blocked/2262/7

Now works like a charm :)

Thanks for your time and effort and for this simple guide for sentry :)

**Comment by mimischi** [comment]
Glad you found the solution to your problem!

If you want to switch, you could go and try out [DigitalOcean.com](https://www.digitalocean.com/). I used them in the past and was quite happy with them.
